server.port=8070
spring.application.name=bff
api.login.path=http://localhost:8080/auth/login
api.passrecover.path=http://localhost:8080/auth/password
api.user.path=http://localhost:8080/users
api.asset.path=http://localhost:8081/assets
api.ticket.path=http://localhost:8082/tickets