server.port=8080
spring.application.name=bff
api.login.path=https://easyadmin-microservice-user.onrender.com/auth/login
api.passrecover.path=https://easyadmin-microservice-user.onrender.com/auth/password
api.user.path=https://easyadmin-microservice-user.onrender.com/users
api.asset.path=https://easyadmin-microservice-asset.onrender.com/assets
api.ticket.path=https://easyadmin-microservice-ticket.onrender.com/tickets